# DATA STRUCTURES NECESSARY FOR THE SOLUTION OF NETWORK EQUATIONS  
Structures $N$: normal matrices

## Matrices from network topology

- $A$: node-arcs incidence matrix of the graph: $M (m, n)$
- $A_r$: submatrix of A corresponding to the reservoirs: $M (m_r, n)$
- $A_d$: complementary submatrix of $Ar$ for $A$: $M (m_d, n)$
- $A_{dT}$: largest invertible square sub-matrix of $A_d$: $M (md, md)$
- $A_{dI}$: inverse matrix of $A_{dT}$: $M (m_d, m_d)$
- $A_{dC}$: complementary submatrix of $A_{dT}$ for $A_d$: $M (m_d, n - m_d)$
- $B$: arcs-cycle incidence matrix of the graph: $M (n, n-m_d)$

## Debit admissible

- $q_0$: vector of the admissible flow rates of the arcs: $M (n, 1)$


## Code

### Import the modular

In [1]:
from numpy import dot
from numpy import eye
from numpy import zeros
from numpy.linalg import inv

### Problem $R\ $: realistic problem

In [4]:
from Probleme_R import *

### Incidence matrix and associated sub-matrices

- Incidence matrix node-arcs of the graph

In [5]:
A = zeros ((m, n))
for i in range (m):
    A [i, orig == i] = -1
    A [i, dest == i] = +1

In [6]:
A

array([[-1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0., -1.,  0.,  0.,  0.,  0.,  0., -1.,  0.],
       [ 0.,  0., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0., -1.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0., -1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0., -1.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0., -1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0., -1., -1.,  0.,  0.,  0.,  0.,
         0.,  0.,  1.,  0.,  0., -1., 

- Switch to integer CSC mode  
  $ A \cdot q=\left(\begin{array}{c}A_{r} \\ A_{d}\end{array}\right) \cdot q=\left(\begin{array}{c}f_{r} \\ f_{d}\end{array}\right) $

- Partition of A according to the type of nodes  
  $ A_r q = f_n$

In [7]:
Ar = A [: mr ,:]
Ad = A [mr: m ,:]

In [8]:
Ar

array([[-1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0., -1.,  0.,  0.,  0.,  0.,  0., -1.,  0.],
       [ 0.,  0., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [9]:
Ad

array([[ 1.,  0.,  0., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0., -1.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0., -1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0., -1.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0., -1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0., -1., -1.,  0.,  0.,  0.,  0.,
         0.,  0.,  1.,  0.,  0., -1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0., -1.,  0.,  0.,  0.,
         0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1., -1.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1., -1.,  0.,
         0.,  0.,  0.,  0.,  1.,  0., 

- Sub-matrix of Ad associated with a tree and inverse  
  $ A_d q = f_d$

In [10]:
AdT = Ad [:,: md]
AdI = inv(AdT)

- Sub-matrix of Ad associated with a co-tree  
  $ A_{d}=\left(A_{d T}, A_{d C}\right) $  
  with  
  $ q=\left(\begin{array}{l}q_{T} \\ q_{C}\end{array}\right) $

In [11]:
AdC = Ad [:, md: n] 

- Matrix of incidence arcs-cycles  
  $$ B=\left(\begin{array}{c}-\left(A_{d T}\right)^{-1} \cdot A_{d C} \\ I\end{array}\right)=\left(\begin{array}{c}B_{1} \\ B_{2}\end{array}\right) $$

In [12]:
B = zeros ((n, n-md))
B [: md ,:] = -dot (AdI, AdC)
B [md:,:] = eye (n-md)

### Vector of admissible flows   
  $$ q_{T}=q_{0}+B q_{C} $$  
  $$ q_{0}=\left(\begin{array}{c}\left(A_{d T}\right)^{-1} \cdot f_{d} \\ 0\end{array}\right) $$

In [13]:
q0 = zeros(n)

In [ ]:
q0 [: md] = dot(AdI, fd)